tree: Events
eras:
  '2016':
    luminosity: 35921.875594646 # pb 
    luminosity-error: 0.025     
samples:
  HToZATo2L2B_MH-1000_MA-200:
    db: das:/HToZATo2L2B_MH-1000_MA-200_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-1000_MA-200_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 7388.0
    line-color: "#e31b1b"
    line-type: 1
    legend: MH-1000_MA-200
    #split: 4
    type: signal

  HToZATo2L2B_MH-1000_MA-500:
    db: das:/HToZATo2L2B_MH-1000_MA-500_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-1000_MA-500_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 10.71 # pb 
    line-color: "#450808"
    line-type: 1
    legend: MH-1000_MA-500
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-1000_MA-50:
    db: das:/HToZATo2L2B_MH-1000_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-1000_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 14930.0  # pb
    line-color: "#080845"
    line-type: 1
    legend: MH-1000_MA-50
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-2000_MA-1000:
    db: das:/HToZATo2L2B_MH-2000_MA-1000_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-2000_MA-1000_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 0.6671 # pb  
    line-color: "#8383f1"
    line-type: 1
    legend: MH-2000_MA-1000 
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-200_MA-100:
    db: das:/HToZATo2L2B_MH-200_MA-100_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-200_MA-100_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 1233000.0 # pb  
    line-color: "#31dce5"
    line-type: 1
    legend: MH-200_MA-100
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-200_MA-50:
    db: das:/HToZATo2L2B_MH-200_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-200_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 1030000.0 # pb  
    line-color: "#e59431"
    line-type: 1
    legend: MH-200_MA-50
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-250_MA-100:
    db: das:/HToZATo2L2B_MH-250_MA-100_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-250_MA-100_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 575200.0 # pb  
    line-color: "#e56731"
    line-type: 1
    legend: MH-250_MA-100
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-250_MA-50:
    db: das:/HToZATo2L2B_MH-250_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-250_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 523200.0 # pb  
    line-color: "#b3175d"
    line-type: 1
    legend: MH-250_MA-50
    #split: 4
    type: signal

  HToZATo2L2B_MH-3000_MA-2000:
    db: das:/HToZATo2L2B_MH-3000_MA-2000_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-3000_MA-2000_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 0.05531 # pb  
    line-color: "#5c1499"
    line-type: 1
    legend: MH-3000_MA-2000
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-300_MA-100:
    db: das:/HToZATo2L2B_MH-300_MA-100_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-300_MA-100_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 323800.0 # pb  
    line-color: "#519914"
    line-type: 1
    legend: MH-300_MA-100
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-300_MA-200:
    db: das:/HToZATo2L2B_MH-300_MA-200_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-300_MA-200_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 325500.0  # pb  
    line-color: "#86777c"
    line-type: 1
    legend: MH-300_MA-200
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-300_MA-50:
    db: das:/HToZATo2L2B_MH-300_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-300_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 294500.0 # pb  
    line-color: "#1b2105"
    line-type: 1
    legend: MH-300_MA-50
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-500_MA-200:
    db: das:/HToZATo2L2B_MH-500_MA-200_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-500_MA-200_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 46430.0 # pb  
    line-color: "#c876ea"
    line-type: 1
    legend: MH-500_MA-200
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-500_MA-300:
    db: das:/HToZATo2L2B_MH-500_MA-300_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-500_MA-300_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 25510.0 # pb  
    line-color: "#76eac8"
    line-type: 1
    legend: MH-500_MA-300
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-500_MA-400:
    db: das:/HToZATo2L2B_MH-500_MA-400_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-500_MA-400_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 9.58 # pb  
    line-color: "#ea8e76"
    line-type: 1
    legend: MH-500_MA-400
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-500_MA-50:
    db: das:/HToZATo2L2B_MH-500_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-500_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 54460.0  # pb  
    line-color: "#a9381a"
    line-type: 1
    legend: MH-500_MA-50
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-650_MA-50:
    db: das:/HToZATo2L2B_MH-650_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-650_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 28750.0 # pb  
    line-color: "#1a8ba9"
    line-type: 1
    legend: MH-650_MA-50
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-800_MA-200:
    db: das:/HToZATo2L2B_MH-800_MA-200_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-800_MA-200_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 12180.0 # pb  
    line-color: "#a91a8b"
    line-type: 1
    legend: MH-800_MA-200
    #split: 4
    type: signal

  HToZATo2L2B_MH-800_MA-400:
    db: das:/HToZATo2L2B_MH-800_MA-400_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-800_MA-400_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 29.24 # pb  
    line-color: "#083211"
    line-type: 1
    legend: MH-800_MA-400
    #split: 4
    type: signal
        
  HToZATo2L2B_MH-800_MA-50:
    db: das:/HToZATo2L2B_MH-800_MA-50_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-800_MA-50_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 19710.0  # pb  
    line-color: "#d3db23"
    line-type: 1
    legend: MH-800_MA-50
    #split: 4
    type: signal 


  HToZATo2L2B_MH-800_MA-700:
    db: das:/HToZATo2L2B_MH-800_MA-700_13TeV-madgraph-pythia8/RunIISummer16NanoAODv5-PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/NANOAODSIM
    files: dascache/HToZATo2L2B_MH-800_MA-700_2016.dat
    generated-events: 'genEventSumw'
    era: '2016'
    cross-section: 1.285 # pb  
    line-color: "#5923db"
    line-type: 1
    legend: MH-800_MA-700
    #split: 4
    type: signal 

plotIt:
  configuration:
    width: 800
    height: 600
    luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
    experiment: CMS
    extra-label: 2016Data --Work in progress
    show-overflow: true
    error-fill-style: 3154
    error-fill-color: "#ee556270"
    ratio-fit-error-fill-style: 1001
    ratio-fit-error-fill-color: "#aa556270"
    ratio-fit-line-color: "#0B486B"
    y-axis-format: "%1% / %2$.2f"

  
  legend:
    position: [0.7, 0.6, 0.91, 0.91]
  
  groups:
    signal:
      fill-color: "#0000FF" 
      legend: Signal
  
  plotdefaults:
      y-axis: Events
      log-y: both
      y-axis-show-zero: True
      save-extensions: [pdf]
      show-ratio: True
      ratio-y-axis-range: [0.6,1.4]
      sort-by-yields: False
  
  systematics:
    # on the jets
    - jer
    - jesTotal
    # on the lepton id /iso 
    - muid
    - muiso
    - elid
      #- ele_reco
      # on the pileup
    - puweights2016_Moriond17
    # on the trigger
    - eleltrig
    - mumutrig
    - elmutrig
    - mueltrig
    # sys from theory  
    - qcdScale
    - psISR
    - psFSR
    # on the btagged jets
    - DeepFlavourL
    - DeepFlavourM
    - DeepFlavourT
    - DeepCSVL
    - DeepCSVM
    - DeepCSVT
    - DeepDoubleBvLL
    - DeepDoubleBvLM1
    - DeepDoubleBvLM2
    - DeepDoubleBvLT1
    - DeepDoubleBvLT2
    # L1 pre-firing event correction weight
    - L1PreFiring
    # on the cross section : 1+xsec_uncert(pb)/xsec(pb)
    - sysonMH-1000_MA-200xsc: {type: const, value: 1.0004113427179209, on: 'HToZATo2L2B_MH-800_MA-50'}   # uncer= 3.039
    - sysonMH-1000_MA-500xsc: {type: const, value: 1.0004113427179209, on: 'HToZATo2L2B_MH-1000_MA-500'}   # uncer=0.006163  
    - sysonMH-1000_MA-50xsc: {type: const, value: 1.0001573342263899, on: 'HToZATo2L2B_MH-1000_MA-50'}   # uncer=2.349
    - sysonMH-2000_MA-1000xsc: {type: const, value: 1.0004561535002248, on: 'HToZATo2L2B_MH-2000_MA-1000'}   # uncer=0.0003043
    - sysonMH-200_MA-100xsc: {type: const, value: 1.00043901054339, on: 'HToZATo2L2B_MH-200_MA-100'}   # uncer=541.3
    - sysonMH-200_MA-50xsc: {type: const, value: 1.0002882524271846, on: 'HToZATo2L2B_MH-200_MA-50'}   # uncer=296.9
    - sysonMH-250_MA-100xsc: {type: const, value: 1.0002858136300417, on: 'HToZATo2L2B_MH-250_MA-100'}   # uncer=164.4
    - sysonMH-250_MA-50xsc: {type: const, value: 1.0003008409785932, on: 'HToZATo2L2B_MH-250_MA-50'}   # uncer=157.4
    - sysonMH-3000_MA-2000xsc: {type: const, value: 1.0001165973603328, on: 'HToZATo2L2B_MH-3000_MA-2000'}   # uncer=6.449e-06
    - sysonMH-300_MA-100xsc: {type: const, value: 1.000296263125386, on: 'HToZATo2L2B_MH-300_MA-100'}   # uncer=95.93
    - sysonMH-300_MA-200xsc: {type: const, value: 1.0004562211981567, on: 'HToZATo2L2B_MH-300_MA-200'}   # uncer=148.5
    - sysonMH-300_MA-50xsc: {type: const, value: 1.0003173514431238, on: 'HToZATo2L2B_MH-300_MA-50'}   # uncer=93.46
    - sysonMH-500_MA-200xsc: {type: const, value: 1.0003144518630196, on: 'HToZATo2L2B_MH-500_MA-200'}   # uncer=14.6
    - sysonMH-500_MA-300xsc: {type: const, value: 1.0003003136025088, on: 'HToZATo2L2B_MH-500_MA-300'}   # uncer=7.661
    - sysonMH-500_MA-400xsc: {type: const, value: 1.000543006263048  , on: 'HToZATo2L2B_MH-500_MA-400'}   # uncer=9.58
    - sysonMH-500_MA-50xsc: {type: const, value: 1.0003321704002939, on: 'HToZATo2L2B_MH-500_MA-50'}   # uncer=18.09
    - sysonMH-650_MA-50xsc: {type: const, value: 1.0003638260869565, on: 'HToZATo2L2B_MH-650_MA-50'}   # uncer=10.46
    - sysonMH-800_MA-200xsc: {type: const, value: 1.0003269293924466, on: 'HToZATo2L2B_MH-800_MA-200'}   # uncer=3.982
    - sysonMH-800_MA-400xsc: {type: const, value: 1.000341997264022, on: 'HToZATo2L2B_MH-800_MA-400'}   # uncer=0.01
    - sysonMH-800_MA-50xsc: {type: const, value: 1.0004281075596144 , on: 'HToZATo2L2B_MH-800_MA-500'}   # uncer= 8.438
    - sysonMH-800_MA-700xsc: {type: const, value: 1.0005445914396887, on: 'HToZATo2L2B_MH-800_MA-700'}   # uncer= 1.285
